version: '3.8'

services:
  # --- App Chat ---
  app-chat:
    build: .
    container_name: chat-app-container
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    environment:
      - PORT=${PORT}
      - MONGODB_URI=mongodb://mongo:27017/chat-app
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

  # --- Database Mongo ---
  mongo:
    image: mongo:latest
    container_name: mongo-db-container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: